### ISSUE TITLE
Download dataset link

### ISSUE THREAD

**Issue by avotiis** [ctr4si/MMN#2]
Hi,

When loading the JSON file into a posts array and checking the length of the array it says that it is 79,949 - this is the length of TIFU-short according to your table. Aren't there supposed to be 120 000 posts in total? 

EDIT: Did not realise that TIFU-long is a subset of TIFU-long. Then it adds up.

**Comment by astariul** [comment]
_More details :_

The JSON actually contain 79,949 lines.
Among these lines, all of them contains title + text, and 42,984 contains title + text + tldr. 

**So it means you have 79,949 examples where the summary of the text is the title (short summary) and 42,984 examples where the summary of the text is the tldr (longer summary).**

(So you have 42,984 where a single text is summarized in 2 ways, short and long, and 36,965 where the text is only short summarized)
